# Generated by Django 6.0.3 on 2026-03-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_storeshowcase_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_label',
            field=models.CharField(blank=True, default='ADD TO BAG', max_length=40),
        ),
        migrations.AddField(
            model_name='storeshowcase',
            name='button_label',
            field=models.CharField(blank=True, default='SAIBA MAIS', max_length=60),
        ),
    ]
