# Generated by Django 6.0.3 on 2026-03-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_button_label_storeshowcase_button_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('subtitulo', models.CharField(blank=True, max_length=180)),
                ('botao_texto', models.CharField(blank=True, max_length=60)),
                ('imagem_fundo', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Banner de Destaque',
                'verbose_name_plural': 'Banners de Destaque',
            },
        ),
        migrations.CreateModel(
            name='CardNovidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_tag', models.CharField(max_length=80)),
                ('imagem', models.URLField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card de Novidade',
                'verbose_name_plural': 'Cards de Novidades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='storeshowcase',
            options={'ordering': ['-active', '-created_at'], 'verbose_name': 'Banner de Vitrine', 'verbose_name_plural': 'Banners de Vitrine'},
        ),
    ]
