# Generated by Django 6.0.3 on 2026-03-29 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bannerdestaque_cardnovidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome da Seção')),
            ],
            options={
                'verbose_name': 'Categoria da Loja',
                'verbose_name_plural': 'Categorias da Loja',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['secao_loja', 'name'], 'verbose_name': 'Produto da Loja', 'verbose_name_plural': 'Produtos da Loja'},
        ),
        migrations.AlterField(
            model_name='product',
            name='button_label',
            field=models.CharField(blank=True, default='ADD TO BAG', max_length=40, verbose_name='Texto do Botão'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Dica: Use fotos verticais com fundo neutro', verbose_name='Foto do Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome da Peça'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.categorysection', verbose_name='Seção'),
        ),
        migrations.AddField(
            model_name='product',
            name='secao_loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='api.secaoloja', verbose_name='Seção onde aparece'),
        ),
    ]
