# Generated by Django 6.0.3 on 2026-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_secaoloja_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerdestaque',
            name='origem_pagina',
            field=models.CharField(choices=[('LOJA', 'LOJA'), ('NOVIDADES', 'NOVIDADES'), ('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO')], default='LOJA', max_length=12, verbose_name='Origem da Página'),
        ),
        migrations.AddField(
            model_name='cardnovidade',
            name='origem_pagina',
            field=models.CharField(choices=[('LOJA', 'LOJA'), ('NOVIDADES', 'NOVIDADES'), ('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO')], default='LOJA', max_length=12, verbose_name='Origem da Página'),
        ),
        migrations.AddField(
            model_name='product',
            name='origem_pagina',
            field=models.CharField(choices=[('LOJA', 'LOJA'), ('NOVIDADES', 'NOVIDADES'), ('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO')], default='LOJA', max_length=12, verbose_name='Origem da Página'),
        ),
        migrations.AddField(
            model_name='storeshowcase',
            name='origem_pagina',
            field=models.CharField(choices=[('LOJA', 'LOJA'), ('NOVIDADES', 'NOVIDADES'), ('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO')], default='LOJA', max_length=12, verbose_name='Origem da Página'),
        ),
    ]
