# Generated by Django 6.0.3 on 2026-03-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bannerdestaque_origem_pagina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardnovidade',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cardnovidades/'),
        ),
    ]
