# Generated by Django 6.0.3 on 2026-03-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cardnovidade_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='secao_loja',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Página do Menu', 'verbose_name_plural': '1. Páginas do Menu'},
        ),
        migrations.AlterModelOptions(
            name='categorysection',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Subcategoria', 'verbose_name_plural': '2. Subcategorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Cadastro de Produto', 'verbose_name_plural': '3. Cadastro de Produtos'},
        ),
        migrations.DeleteModel(
            name='SecaoLoja',
        ),
    ]
