# Generated by Django 6.0.3 on 2026-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_product_secao_loja_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, help_text='Dica: Use fotos verticais com fundo neutro', null=True, upload_to='products/', verbose_name='Foto do Produto'),
        ),
    ]
