# Generated by Django 6.0.3 on 2026-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemininoProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Produto Feminino',
                'verbose_name_plural': 'Produtos Feminino',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='LojaProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Produto Loja',
                'verbose_name_plural': 'Produtos Loja',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='MasculinoProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Produto Masculino',
                'verbose_name_plural': 'Produtos Masculino',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
        migrations.CreateModel(
            name='NovidadeProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Produto Novidades',
                'verbose_name_plural': 'Produtos Novidades',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.product',),
        ),
        migrations.AddField(
            model_name='category',
            name='origem_pagina',
            field=models.CharField(choices=[('LOJA', 'LOJA'), ('NOVIDADES', 'NOVIDADES'), ('FEMININO', 'FEMININO'), ('MASCULINO', 'MASCULINO')], default='LOJA', max_length=12, verbose_name='Menu da Navbar'),
        ),
    ]
